### ISSUE TITLE
Responsive Design: revamp CSS for desktop

### ISSUE THREAD

**Issue by AdelBeit** [AdelBeit/dnk#3]
Need to make the app more responsive and add breakpoints for desktops to make it look nicer and more playable on touchscreen laptops and desktops.

**Comment by pedroagcf** [comment]
Hey I can help with that

**Comment by AdelBeit** [comment]
I just saw this, I actually just finished updating it with responsive design. 
commit: f95cecaa10d2f36a454e4a5a69bad868e463d910
